# -- Hauptmenü --
# Das Hauptmenü wird in der Kopfzeile oben auf der Seite angezeigt.

[[main]]
  name = "Start"
  pageRef = "/"
  weight = 10

[[main]]
  name = "Entdecken"
  weight = 20

[[main]]
  name = "Übersicht"
  parent = "Entdecken"
  pageRef = "overview"
  weight = 16

[[main]]
  name = "Beiträge"
  parent = "Entdecken"
  pageRef = "posts"
  weight = 17

[[main]]
  name = "Kategorien"
  parent = "Entdecken"
  pageRef = "categories"
  weight = 18

[[main]]
  name = "Serien"
  parent = "Entdecken"
  pageRef = "series"
  weight = 19

[[main]]
  name = "Tags"
  parent = "Entdecken"
  pageRef = "tags"
  weight = 20

[[main]]
  name = "Profil"
  pageRef = "about"
  weight = 30

  #[[main]]
  #  identifier = "mastodon"
  #  pre = "mastodon"
  #  weight = 300
  #  url = "https://mastodon.social/@sebastianzehner"

  #[[main]]
  #  identifier = "github"
  #  pre = "github"
  #  url = "https://github.com/sebastianzehner/blog"
  #  weight = 400


  # -- Fußzeilenmenü --

[[footer]]
  name = "Wetter und Livecam"
  pageRef = "livecam"
  weight = 10

[[footer]]
  name = "Newsletter"
  pageRef = "newsletter"
  weight = 20
