# -- Menú Principal --
# El menú principal se muestra en el encabezado en la parte superior de la página.

[[main]]
  name = "Inicio"
  pageRef = "/"
  weight = 10

[[main]]
  name = "Descubrir"
  weight = 20

[[main]]
  name = "Visión general"
  parent = "Descubrir"
  pageRef = "overview"
  weight = 16

[[main]]
  name = "Entradas"
  parent = "Descubrir"
  pageRef = "posts"
  weight = 17

[[main]]
  name = "Categorías"
  parent = "Descubrir"
  pageRef = "categories"
  weight = 18

[[main]]
  name = "Series"
  parent = "Descubrir"
  pageRef = "series"
  weight = 19

[[main]]
  name = "Tags"
  parent = "Descubrir"
  pageRef = "tags"
  weight = 20

[[main]]
  name = "Perfil"
  pageRef = "about"
  weight = 30

  #[[main]]
  #  identifier = "mastodon"
  #  pre = "mastodon"
  #  weight = 300
  #  url = "https://mastodon.social/@sebastianzehner"

  #[[main]]
  #  identifier = "github"
  #  pre = "github"
  #  url = "https://github.com/sebastianzehner/blog"
  #  weight = 400


  # -- Menú de Pie de Página --

[[footer]]
  name = "Clima y Livecam"
  pageRef = "livecam"
  weight = 10

[[footer]]
  name = "Newsletter"
  pageRef = "newsletter"
  weight = 20
