baseURL = 'https://sebastianzehner.com'
#baseURL = 'localhost' #testing at local server
languageCode = 'en-us'
title = 'Sebastian Zehner'
summary = 'This is my personal blog and I am writing about projects I have been working on and what I learn along the way. I also share some private experiences or adventures of my life.'
theme = 'PaperMod'

goatcounter = 'stats'

enableEmoji = true

enableGitInfo = true

[privacy]
  [privacy.youtube]
    disable = false
    privacyEnhanced = true

[frontmatter]
lastmod = ["lastmod", ":git", "date", "publishDate"]

[outputs]
    home = [ "HTML", "RSS", "JSON" ]

[params]
    ShowBreadCrumbs = true
    ShowShareButtons = true
    ShareButtons = ["facebook", "x", "telegram", "whatsapp"]
    ShowCodeCopyButtons = true
    ShowPostNavLinks = false
    ShowReadingTime = true
    ShowWordCount = true
    ShowPageViews = true
    ShowRssButtonInSectionTermList = true

    label.icon = "/img/sz-light.png"
    label.text = "-"
    label.iconHeight = "50"

    defaultTheme = 'auto'
    disableThemeToggle = false

[params.homeInfoParams]
    title = '''Hey, I'm Sebastian :wave:'''
    #content = '**test** und *test* > blockquote  und so weiter `code` linie --- und noch was? # Heading'
    content = '''Welcome to my personal website. This is my minimalistic blog where I share projects I've been working on and what I learn along the way. I also share some private experiences or adventures of my life. You'll find more about me in the menu :point_up: The standard language is English but you can switch to German or Spanish for the translated version. Have fun and :walking: through my blog. | --> *I'm still in progress with translation!*'''
    [[params.socialIcons]]
        name = 'facebook'
        url = 'https://www.facebook.com/sebastianzehner83'
    [[params.socialIcons]]
        name = 'instagram'
        url = 'https://www.instagram.com/sebastianzehner/'
    [[params.socialIcons]]
        name = 'youtube'
        url = 'https://www.youtube.com/@SebastianZehner'
    [[params.socialIcons]]
        name = 'matrix'
        url = 'https://matrix.to/#/@sebastianzehner:matrix.org'

defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true
[languages]
  [languages.en]
    languageCode = 'en-US'
    languageName = 'English'
    weight = 1
    [languages.en.menus]
        [[languages.en.menus.main]]
            name = 'Home'
            pageRef = '/'
            weight = 10
        [[languages.en.menus.main]]
            identifier = 'categories'
            name = 'Categories'
            pageRef = '/categories/'
            weight = 20
        [[languages.en.menus.main]]
            identifier = 'tags'
            name = 'Tags'
            pageRef = '/tags/'
            weight = 30
        [[languages.en.menus.main]]
            identifier = 'archives'
            name = 'Archives'
            pageRef = '/archives/'
            weight = 40
        [[languages.en.menus.main]]
            name = 'About'
            pageRef = '/about/'
            weight = 50
        [[languages.en.menus.main]]
            identifier = 'search'
            name = 'Search'
            pageRef = '/search/'
            weight = 60
  [languages.de]
    languageCode = 'de-DE'
    languageName = 'Deutsch'
    weight = 2
    [languages.de.menus]
        [[languages.de.menus.main]]
            name = 'Start'
            pageRef = '/'
            weight = 10
        [[languages.de.menus.main]]
            identifier = 'categories'
            name = 'Kategorien'
            pageRef = '/categories/'
            weight = 20
        [[languages.de.menus.main]]
            identifier = 'tags'
            name = 'Tags'
            pageRef = '/tags/'
            weight = 30
        [[languages.de.menus.main]]
            identifier = 'archives'
            name = 'Archiv'
            pageRef = '/archives/'
            weight = 40
        [[languages.de.menus.main]]
            name = 'Über'
            pageRef = '/about/'
            weight = 50
        [[languages.de.menus.main]]
            identifier = 'search'
            name = 'Suche'
            pageRef = '/search/'
            weight = 60
  [languages.es]
    languageCode = 'es-ES'
    languageName = 'Español'
    weight = 3
    [languages.es.menus]
        [[languages.es.menus.main]]
            name = 'Inicio'
            pageRef = '/'
            weight = 10
        [[languages.es.menus.main]]
            identifier = 'categories'
            name = 'Categorías'
            pageRef = '/categories/'
            weight = 20
        [[languages.es.menus.main]]
            identifier = 'tags'
            name = 'Tags'
            pageRef = '/tags/'
            weight = 30
        [[languages.es.menus.main]]
            identifier = 'archives'
            name = 'Archivo'
            pageRef = '/archives/'
            weight = 40
        [[languages.es.menus.main]]
            name = 'Sobre'
            pageRef = '/about/'
            weight = 50
        [[languages.es.menus.main]]
            identifier = 'search'
            name = 'Buscar'
            pageRef = '/search/'
            weight = 60

#Archives not available with multilingual. Same as categories and tags. How to fix?
#Archives are multilingual! It works fine.