baseURL = 'https://sebastianzehner.com'
#baseURL = 'localhost' #testing at local server
languageCode = 'en-us'
title = 'sebastianzehner.com'
theme = 'PaperMod'

enableEmoji = true

[params]
    ShowBreadCrumbs = true
    ShowShareButtons = true
    ShowCodeCopyButtons = true
    #ShowReadingTime = true
    #ShowPostNavLinks = false

    defaultTheme = 'auto'
    disableThemeToggle = false

    goatcounter = 'stats'

[params.homeInfoParams]
    title = 'Hi there... :wave:'
    content = 'Welcome to my personal website. This is my minimalistic blog where I share projects I have been working on and what I learn along the way. I also share some private experiences or adventures of my life. You will find more about me [here](/about/). The standard language is English but you can switch to German or Spanish with only one click.'
    [[params.socialIcons]]
        name = 'facebook'
        url = 'https://www.facebook.com/sebastianzehner83'
    [[params.socialIcons]]
        name = 'instagram'
        url = 'https://www.instagram.com/sebastianzehner/'
    [[params.socialIcons]]
        name = 'youtube'
        url = 'https://www.youtube.com/@SebastianZehner'

defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true
[languages]
  [languages.en]
    languageCode = 'en-US'
    languageName = 'English'
    weight = 1
    [languages.en.menus]
        [[languages.en.menus.main]]
            name = 'Home'
            pageRef = '/'
            weight = 10
        [[languages.en.menus.main]]
            identifier = 'categories'
            name = 'Categories'
            pageRef = '/categories/'
            weight = 20
        [[languages.en.menus.main]]
            identifier = 'tags'
            name = 'Tags'
            pageRef = '/tags/'
            weight = 30
        [[languages.en.menus.main]]
            identifier = 'archives'
            name = 'Archives'
            pageRef = '/archives/'
            weight = 40
        [[languages.en.menus.main]]
            name = 'About'
            pageRef = '/about/'
            weight = 50
  [languages.de]
    languageCode = 'de-DE'
    languageName = 'Deutsch'
    weight = 2
    [languages.de.menus]
        [[languages.de.menus.main]]
            name = 'Start'
            pageRef = '/'
            weight = 10
        [[languages.de.menus.main]]
            identifier = 'categories'
            name = 'Kategorien'
            pageRef = '/categories/'
            weight = 20
        [[languages.de.menus.main]]
            identifier = 'tags'
            name = 'Tags'
            pageRef = '/tags/'
            weight = 30
        [[languages.de.menus.main]]
            identifier = 'archives'
            name = 'Archiv'
            pageRef = '/archives/'
            weight = 40
  [languages.es]
    languageCode = 'es-ES'
    languageName = 'Español'
    weight = 3
    [languages.es.menus]
        [[languages.es.menus.main]]
            name = 'Inicio'
            pageRef = '/'
            weight = 10
        [[languages.es.menus.main]]
            identifier = 'categories'
            name = 'Categorías'
            pageRef = '/categories/'
            weight = 20
        [[languages.es.menus.main]]
            identifier = 'tags'
            name = 'Tags'
            pageRef = '/tags/'
            weight = 30
        [[languages.es.menus.main]]
            identifier = 'archives'
            name = 'Archivo'
            pageRef = '/archives/'
            weight = 40


#Archives not available with multilingual. Same as categories and tags. How to fix?
#Archives are multilingual! It works fine.